openapi: 3.0.3
info:
    title: mental-clinic.social General Service
    description: Service for general users
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /health_check:
        get:
            tags:
                - general
            summary: healthCheck general
            operationId: general#healthCheck
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HealthCheckResult'
                            example:
                                status: Veniam occaecati autem nostrum consequuntur.
    /openapi.json:
        get:
            tags:
                - general
            summary: Download ./gen/http/openapi.json
            operationId: general#/openapi.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        HealthCheckResult:
            type: object
            properties:
                status:
                    type: string
                    description: Status of the service
                    example: Perspiciatis et est.
            example:
                status: Accusantium sunt maiores ut.
tags:
    - name: general
      description: Service for general users
