swagger: "2.0"
info:
    title: mental-clinic.social General Service
    description: Service for general users
    version: 0.0.1
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /auth:
        get:
            tags:
                - general
            summary: auth general
            operationId: general#auth
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/GeneralAuthResponseBody'
                        required:
                            - authURL
            schemes:
                - http
    /health_check:
        get:
            tags:
                - general
            summary: healthCheck general
            operationId: general#healthCheck
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/GeneralHealthCheckResponseBody'
                        required:
                            - status
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - general
            summary: Download ./gen/http/openapi.json
            operationId: general#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    GeneralAuthResponseBody:
        title: GeneralAuthResponseBody
        type: object
        properties:
            authURL:
                type: string
                description: URL for authorization
                example: Eos reiciendis.
        example:
            authURL: Error pariatur qui animi est voluptatibus.
        required:
            - authURL
    GeneralHealthCheckResponseBody:
        title: GeneralHealthCheckResponseBody
        type: object
        properties:
            status:
                type: string
                description: Status of the service
                example: Perspiciatis et est.
        example:
            status: Accusantium sunt maiores ut.
        required:
            - status
